var searchData=
[
  ['validator_0',['Validator',['../dd/dd7/interfacegames_1_1stendhal_1_1server_1_1core_1_1rp_1_1equipping_1_1validator_1_1Validator.htm',1,'games.stendhal.server.core.rp.equipping.validator.Validator'],['../df/d47/classmarauroa_1_1common_1_1game_1_1Validator.htm',1,'marauroa.common.game.Validator']]],
  ['validatorlist_1',['ValidatorList',['../da/dcc/classgames_1_1stendhal_1_1server_1_1core_1_1account_1_1ValidatorList.htm',1,'games::stendhal::server::core::account']]],
  ['vampirelordcreature_2',['VampireLordCreature',['../de/d2f/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1catacombs_1_1VampireLordCreature.htm',1,'games::stendhal::server::maps::semos::catacombs']]],
  ['vampiresword_3',['VampireSword',['../d3/dd4/classgames_1_1stendhal_1_1server_1_1maps_1_1quests_1_1VampireSword.htm',1,'games::stendhal::server::maps::quests']]],
  ['variables_4',['Variables',['../de/dff/classmarauroa_1_1server_1_1game_1_1Statistics_1_1Variables.htm',1,'marauroa::server::game::Statistics']]],
  ['variablespriteentity2dview_5',['VariableSpriteEntity2DView',['../df/d68/classgames_1_1stendhal_1_1client_1_1gui_1_1j2d_1_1entity_1_1VariableSpriteEntity2DView.htm',1,'games::stendhal::client::gui::j2d::entity']]],
  ['variablespriteentity2dview_3c_20t_20_3e_6',['VariableSpriteEntity2DView&lt; T &gt;',['../df/d68/classgames_1_1stendhal_1_1client_1_1gui_1_1j2d_1_1entity_1_1VariableSpriteEntity2DView.htm',1,'games::stendhal::client::gui::j2d::entity']]],
  ['variablewidthmenuitem_7',['VariableWidthMenuItem',['../d7/dcd/classgames_1_1stendhal_1_1client_1_1gui_1_1SettingsPanel_1_1VariableWidthMenuItem.htm',1,'games::stendhal::client::gui::SettingsPanel']]],
  ['vault_8',['Vault',['../d4/d51/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1bank_1_1Vault.htm',1,'games::stendhal::server::maps::semos::bank']]],
  ['vaultchataction_9',['VaultChatAction',['../d6/d08/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1bank_1_1CustomerAdvisorNPC_1_1VaultChatAction.htm',1,'games::stendhal::server::maps::semos::bank::CustomerAdvisorNPC']]],
  ['vaultmovementlistener_10',['VaultMovementListener',['../d1/d1c/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1bank_1_1Vault_1_1VaultMovementListener.htm',1,'games::stendhal::server::maps::semos::bank::Vault']]],
  ['vaultremover_11',['VaultRemover',['../d6/d8b/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1bank_1_1VaultRemover.htm',1,'games::stendhal::server::maps::semos::bank']]],
  ['vdirection_12',['VDirection',['../d6/d6a/classgames_1_1stendhal_1_1client_1_1gui_1_1layout_1_1SBoxLayout_1_1VDirection.htm',1,'games::stendhal::client::gui::layout::SBoxLayout']]],
  ['vector_13',['Vector',['https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Vector.html',1,'java::util']]],
  ['vector_3c_20byte_5b_5d_3e_14',['Vector&lt; byte[]&gt;',['https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Vector.html',1,'java::util']]],
  ['vegetablegrower_15',['VegetableGrower',['../d5/d07/classgames_1_1stendhal_1_1server_1_1entity_1_1mapstuff_1_1spawner_1_1VegetableGrower.htm',1,'games::stendhal::server::entity::mapstuff::spawner']]],
  ['verb_16',['Verb',['../d7/dbe/classgames_1_1stendhal_1_1common_1_1grammar_1_1Grammar_1_1Verb.htm',1,'games.stendhal.common.grammar.Grammar.Verb'],['../d4/dfb/classgames_1_1stendhal_1_1common_1_1parser_1_1WordList_1_1Verb.htm',1,'games.stendhal.common.parser.WordList.Verb']]],
  ['vergernpc_17',['VergerNPC',['../d3/d13/classgames_1_1stendhal_1_1server_1_1maps_1_1ados_1_1church_1_1VergerNPC.htm',1,'games.stendhal.server.maps.ados.church.VergerNPC'],['../d4/da4/classgames_1_1stendhal_1_1server_1_1maps_1_1fado_1_1church_1_1VergerNPC.htm',1,'games.stendhal.server.maps.fado.church.VergerNPC']]],
  ['version_18',['Version',['../d5/d79/classgames_1_1stendhal_1_1common_1_1Version.htm',1,'games::stendhal::common']]],
  ['versionstate_19',['VersionState',['../d3/d30/enumgames_1_1stendhal_1_1client_1_1update_1_1VersionState.htm',1,'games::stendhal::client::update']]],
  ['verticalalignment_20',['VerticalAlignment',['../d8/d02/enumgames_1_1stendhal_1_1client_1_1gui_1_1j2d_1_1entity_1_1helpers_1_1VerticalAlignment.htm',1,'games::stendhal::client::gui::j2d::entity::helpers']]],
  ['verticalscollbarmodel_21',['VerticalScollbarModel',['../da/d07/classgames_1_1stendhal_1_1client_1_1gui_1_1KTextEdit_1_1VerticalScollbarModel.htm',1,'games::stendhal::client::gui::KTextEdit']]],
  ['veterinariannpc_22',['VeterinarianNPC',['../d5/dab/classgames_1_1stendhal_1_1server_1_1maps_1_1ados_1_1outside_1_1VeterinarianNPC.htm',1,'games::stendhal::server::maps::ados::outside']]],
  ['vialontable_23',['VialOnTable',['../da/da1/classgames_1_1stendhal_1_1server_1_1maps_1_1semos_1_1apothecary__lab_1_1VialOnTable.htm',1,'games::stendhal::server::maps::semos::apothecary_lab']]],
  ['viewchangeentity_24',['ViewChangeEntity',['../db/d6b/classgames_1_1stendhal_1_1server_1_1entity_1_1mapstuff_1_1useable_1_1ViewChangeEntity.htm',1,'games::stendhal::server::entity::mapstuff::useable']]],
  ['viewchangeentityfactory_25',['ViewChangeEntityFactory',['../d5/d86/classgames_1_1stendhal_1_1server_1_1entity_1_1mapstuff_1_1useable_1_1ViewChangeEntityFactory.htm',1,'games::stendhal::server::entity::mapstuff::useable']]],
  ['viewchangeevent_26',['ViewChangeEvent',['../d9/dff/classgames_1_1stendhal_1_1client_1_1events_1_1ViewChangeEvent.htm',1,'games.stendhal.client.events.ViewChangeEvent'],['../d3/d17/classgames_1_1stendhal_1_1server_1_1events_1_1ViewChangeEvent.htm',1,'games.stendhal.server.events.ViewChangeEvent']]],
  ['viewpanel_27',['ViewPanel',['../d5/d3a/classgames_1_1stendhal_1_1client_1_1gui_1_1imageviewer_1_1ViewPanel.htm',1,'games::stendhal::client::gui::imageviewer']]],
  ['visualsettings_28',['VisualSettings',['../d9/d6f/classgames_1_1stendhal_1_1client_1_1gui_1_1settings_1_1VisualSettings.htm',1,'games::stendhal::client::gui::settings']]],
  ['volatileimage_29',['VolatileImage',['https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/awt/image/VolatileImage.html',1,'java::awt::image']]],
  ['volumeaction_30',['VolumeAction',['../df/d12/classgames_1_1stendhal_1_1client_1_1actions_1_1VolumeAction.htm',1,'games::stendhal::client::actions']]],
  ['volumeadjustor_31',['VolumeAdjustor',['../dd/dda/classgames_1_1stendhal_1_1client_1_1sound_1_1system_1_1processors_1_1SoundLayers_1_1VolumeAdjustor.htm',1,'games.stendhal.client.sound.system.processors.SoundLayers.VolumeAdjustor'],['../d4/de3/classgames_1_1stendhal_1_1client_1_1sound_1_1system_1_1processors_1_1VolumeAdjustor.htm',1,'games.stendhal.client.sound.system.processors.VolumeAdjustor']]],
  ['volumegroups_32',['VolumeGroups',['../dd/d47/classgames_1_1stendhal_1_1client_1_1sound_1_1system_1_1processors_1_1VolumeGroups.htm',1,'games::stendhal::client::sound::system::processors']]]
];
