var searchData=
[
  ['android_0',['android',['https://developer.android.com/reference/android/app/package-summary.html',1,'']]],
  ['androidx_1',['androidx',['https://developer.android.com/reference/androidx/appcompat/app/package-summary.html',1,'']]],
  ['app_2',['app',['https://developer.android.com/reference/android/app/package-summary.html',1,'android::app'],['https://developer.android.com/reference/androidx/appcompat/app/package-summary.html',1,'androidx::appcompat::app']]],
  ['appcompat_3',['appcompat',['https://developer.android.com/reference/androidx/appcompat/app/package-summary.html',1,'androidx']]],
  ['content_4',['content',['https://developer.android.com/reference/android/content/package-summary.html',1,'android']]],
  ['drawable_5',['drawable',['https://developer.android.com/reference/android/graphics/drawable/package-summary.html',1,'android::graphics']]],
  ['graphics_6',['graphics',['https://developer.android.com/reference/android/graphics/drawable/package-summary.html',1,'android']]],
  ['inputmethod_7',['inputmethod',['https://developer.android.com/reference/android/view/inputmethod/package-summary.html',1,'android::view']]],
  ['os_8',['os',['https://developer.android.com/reference/android/os/package-summary.html',1,'android']]],
  ['pm_9',['pm',['https://developer.android.com/reference/android/content/pm/package-summary.html',1,'android::content']]],
  ['res_10',['res',['https://developer.android.com/reference/android/content/res/package-summary.html',1,'android::content']]],
  ['text_11',['text',['https://developer.android.com/reference/android/text/package-summary.html',1,'android']]],
  ['util_12',['util',['https://developer.android.com/reference/android/util/package-summary.html',1,'android']]],
  ['view_13',['view',['https://developer.android.com/reference/android/view/package-summary.html',1,'android']]],
  ['webkit_14',['webkit',['https://developer.android.com/reference/android/webkit/package-summary.html',1,'android']]],
  ['widget_15',['widget',['https://developer.android.com/reference/android/widget/package-summary.html',1,'android']]]
];
